version: '2'
services:
  mongo:
   image: mongo:latest
   container_name: mongo
   ports:
    - "27017:27017"
   volumes:
    - E:\Code\mongodata:/data/db

  thorbot:
    image: thorbot:test
    container_name: thorbot
